.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH SAT4J 1 "June  8, 2008"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
sat4j \- efficient library of SAT solvers in Java
.SH SYNOPSIS
.B sat4j
.I input-file
.SH DESCRIPTION
This manual page documents briefly the
.B sat4j
command.
.PP
.\" TeX users may be more comfortable with the \fB<whatever>\fP and
.\" \fI<whatever>\fP escape sequences to invode bold face and italics, 
.\" respectively.
\fBsat4j\fP is an efficient library for SAT solvers written in Java.
.PP
An initial set of documentation can be found at
http://www.sat4j.org/doc.php (in particular the "getting started guide" is
recommended). This documentation is not shipped in the package as it is not
DFSG-free.
.SH AUTHOR
sat4j was written by Daniel Le Berre.
.PP
This manual page was written by Michael Tautschnig <mt@debian.org>,
for the Debian project (but may be used by others).
